# Generated by Django 6.0.2 on 2026-02-19 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('annio', models.PositiveIntegerField()),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videojuegos', to='catalogo.genero')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videojuegos', to='catalogo.plataforma')),
            ],
        ),
    ]
